# Copyright 2026 bburda
# SPDX-License-Identifier: Apache-2.0
"""Triggers API - trigger management and event streaming."""

from ros2_medkit_client._generated.api.triggers import (
    create_app_trigger,
    create_area_trigger,
    create_component_trigger,
    create_function_trigger,
    delete_app_trigger,
    delete_area_trigger,
    delete_component_trigger,
    delete_function_trigger,
    get_app_trigger,
    get_area_trigger,
    get_component_trigger,
    get_function_trigger,
    list_app_triggers,
    list_area_triggers,
    list_component_triggers,
    list_function_triggers,
    stream_app_trigger_events,
    stream_area_trigger_events,
    stream_component_trigger_events,
    stream_function_trigger_events,
    update_app_trigger,
    update_area_trigger,
    update_component_trigger,
    update_function_trigger,
)

__all__ = [
    "create_app_trigger",
    "create_area_trigger",
    "create_component_trigger",
    "create_function_trigger",
    "delete_app_trigger",
    "delete_area_trigger",
    "delete_component_trigger",
    "delete_function_trigger",
    "get_app_trigger",
    "get_area_trigger",
    "get_component_trigger",
    "get_function_trigger",
    "list_app_triggers",
    "list_area_triggers",
    "list_component_triggers",
    "list_function_triggers",
    "stream_app_trigger_events",
    "stream_area_trigger_events",
    "stream_component_trigger_events",
    "stream_function_trigger_events",
    "update_app_trigger",
    "update_area_trigger",
    "update_component_trigger",
    "update_function_trigger",
]
